export const IPC = {
  SSH_CONNECT: 'ssh:connect',
  SSH_DISCONNECT: 'ssh:disconnect',
  SSH_DISCONNECT_ALL: 'ssh:disconnect-all',
  SSH_STATUS: 'ssh:status',
  SSH_STATUS_UPDATE: 'ssh:status-update',
  SSH_CONFIG_READ: 'ssh:config-read',
  SSH_CONFIG_HOSTS: 'ssh:config-hosts',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  ALIASES_GET: 'aliases:get',
  ALIASES_SAVE: 'aliases:save',
  ALIASES_DELETE: 'aliases:delete',
  TERMINAL_OPEN: 'terminal:open',
  TERMINAL_CLOSE: 'terminal:close',
  TERMINAL_DATA: 'terminal:data',
  TERMINAL_DATA_OUT: 'terminal:data-out',
  TERMINAL_RESIZE: 'terminal:resize',
  DIALOG_OPEN_FILE: 'dialog:open-file',
} as const
